export const GET_CARD         = 'GET_CARD';
export const GET_CARD_SUCCESS = 'GET_CARD_SUCCESS';
export const GET_CARD_FAILED  = 'GET_CARD_FAILED';

export const GET_CARDS         = 'GET_CARDS';
export const GET_CARDS_SUCCESS = 'GET_CARDS_SUCCESS';
export const GET_CARDS_FAILED  = 'GET_CARDS_FAILED';

export const UPLOAD_CARD         = 'UPLOAD_CARD';
export const UPLOAD_CARD_SUCCESS = 'UPLOAD_CARD_SUCCESS';
export const UPLOAD_CARD_FAILED  = 'UPLOAD_CARD_FAILED';

export const UPDATE_CARD         = 'UPDATE_CARD';
export const UPDATE_CARD_SUCCESS = 'UPDATE_CARD_SUCCESS';
export const UPDATE_CARD_FAILED  = 'UPDATE_CARD_FAILED';

export const DELETE_CARD         = 'DELETE_CARD';
export const DELETE_CARD_SUCCESS = 'DELETE_CARD_SUCCESS';
export const DELETE_CARD_FAILED  = 'DELETE_CARD_FAILED';
